### PR TITLE
Forgot Opera in one spot in README. Whoops.

### PR DESCRIPTION
**Pull request by NekoJonez**

### CODE REVIEW

**Comment by NekoJonez** [comment]
In terms of Opera, shouldn't we mention the fact that the extension: https://addons.opera.com/en/extensions/details/install-chrome-extensions/ should be installed as well for this to work flawlessly? @vlad-timotei

**Comment by vlad-timotei** [comment]
> In terms of Opera, shouldn't we mention the fact that the extension: https://addons.opera.com/en/extensions/details/install-chrome-extensions/ should be installed as well for this to work flawlessly? @vlad-timotei

I'll have to test it in Opera. I don't know how it works. If there is a needed addon, then yes, that should be specified. 

I am closing this, as in branch [one.four](https://github.com/vlad-timotei/wpgp-tools/tree/one.four) that line you missed will be replaced 😃.

**Comment by vlad-timotei** [comment]
@NekoJonez feel free to add a comment here if you have additional information on how it works in Opera.

**Comment by NekoJonez** [comment]
I'll wait till the one.four branch is published and then write up how it works in Opera ;)

**Comment by vlad-timotei** [comment]
You could submit a PR for that branch [here](https://github.com/vlad-timotei/wpgp-tools/tree/one.four).

**Pull request closed without merging**
